<?php

declare(strict_types=1);

class CoreSourceInventoryTest extends \PHPUnit\Framework\TestCase
{
    private function getDiscoveredSourceFiles(): array
    {
        return [
            '_core/base/data.php',
            '_core/base/meta/delayed.php',
            '_core/base/meta/maker.php',
            '_core/base/meta/row.php',
            '_core/base/model/entity.php',
            '_core/base/model/file_data/entity.php',
            '_core/base/model/file_data/row.php',
            '_core/base/model/request.php',
            '_core/base/model/row.php',
            '_core/base/model/rowset.php',
            '_core/base/model/spec_file/entity.php',
            '_core/base/model/spec_file/image/entity.php',
            '_core/base/model/spec_file/image/row.php',
            '_core/base/model/spec_file/row.php',
            '_core/base/service.php',
            '_core/base/service/multi.php',
            '_core/base/service/single.php',
            '_core/base/timer_program.php',
            '_core/base/transfer.php',
            '_core/base/transfer/int.php',
            '_core/base/transfer/out.php',
            '_core/base/transfer/sham.php',
            '_core/base/transfer/transfer_int.php',
            '_core/block/admin/base.php',
            '_core/block/admin/data.meta.php',
            '_core/block/admin/data.php',
            '_core/block/admin/data_form.meta.php',
            '_core/block/admin/data_form.php',
            '_core/block/admin/data_info.meta.php',
            '_core/block/admin/data_info.php',
            '_core/block/admin/data_table.meta.php',
            '_core/block/admin/data_table.php',
            '_core/block/admin/form_pattern.meta.php',
            '_core/block/admin/form_pattern.php',
            '_core/block/admin/index.meta.php',
            '_core/block/admin/index.php',
            '_core/block/admin/root.meta.php',
            '_core/block/admin/root.php',
            '_core/block/admin/select_dependent.php',
            '_core/block/admin/structure.meta.php',
            '_core/block/admin/structure.php',
            '_core/block/admin/upload_file.php',
            '_core/block/admin/upload_flash.php',
            '_core/block/admin/upload_image.php',
            '_core/block/base.php',
            '_core/block/common/html_nav.php',
            '_core/block/common/html_nav_db.php',
            '_core/block/common/html_pager.meta.php',
            '_core/block/common/html_pager.php',
            '_core/block/common/html_pager_quantifier.meta.php',
            '_core/block/common/html_pager_quantifier.php',
            '_core/block/common/simple.php',
            '_core/block/error/error403.php',
            '_core/block/error/error404.php',
            '_core/block/error/error500.php',
            '_core/block/form/parser.meta.php',
            '_core/block/form/parser.php',
            '_core/block/form/part.php',
            '_core/block/form/usual.meta.php',
            '_core/block/form/usual.php',
            '_core/block/loader/base.php',
            '_core/block/loader/loader_form_validation.php',
            '_core/block/root/html.meta.php',
            '_core/block/root/html.php',
            '_core/bootstrap.php',
            '_core/bootstrap/initializer.php',
            '_core/bootstrap/loader.php',
            '_core/bootstrap/runner.php',
            '_core/cli/restore_password.php',
            '_core/error/demonstrator.php',
            '_core/error/template/default.php',
            '_core/error/template/error_403.php',
            '_core/error/template/error_404.php',
            '_core/error/template/error_500.php',
            '_core/exception/base.php',
            '_core/exception/block/fatal.php',
            '_core/exception/block/form_part.php',
            '_core/exception/block/local.php',
            '_core/exception/error500.php',
            '_core/exception/fatal.php',
            '_core/exception/model/entity/fatal.php',
            '_core/exception/model/reverse.php',
            '_core/exception/plain/fatal.php',
            '_core/exception/service/database.php',
            '_core/exception/service/date.php',
            '_core/exception/service/fatal.php',
            '_core/exception/template/fatal.php',
            '_core/functions.php',
            '_core/ini_cli.php',
            '_core/plain/captcha.php',
            '_core/plain/db_file.php',
            '_core/plain/image.php',
            '_core/plain/obfuscator.php',
            '_core/plain/video.php',
            '_core/service/application.php',
            '_core/service/cache.php',
            '_core/service/cache/base.php',
            '_core/service/cache/file.php',
            '_core/service/cache/memcache.php',
            '_core/service/cache/memcached.php',
            '_core/service/cache/wrapper/file_data.php',
            '_core/service/captcha.php',
            '_core/service/captcha/base.php',
            '_core/service/captcha/file_maker/picture_1.php',
            '_core/service/captcha/text_generator/simple.php',
            '_core/service/cli.php',
            '_core/service/config.php',
            '_core/service/config/arr.php',
            '_core/service/config/base.php',
            '_core/service/config/ini.php',
            '_core/service/config/row.php',
            '_core/service/config/xml.php',
            '_core/service/config/yaml.php',
            '_core/service/cookie.php',
            '_core/service/curl.php',
            '_core/service/database.php',
            '_core/service/database/adodb.php',
            '_core/service/database/base.php',
            '_core/service/database/mysql.php',
            '_core/service/database/mysqlImproved.php',
            '_core/service/database/mysqlPdo.php',
            '_core/service/date.php',
            '_core/service/debug.php',
            '_core/service/email.php',
            '_core/service/email/phpmailer.php',
            '_core/service/entity.php',
            '_core/service/entity/description.php',
            '_core/service/entity/descriptor.php',
            '_core/service/entity/descriptor/mysql.php',
            '_core/service/entity/descriptor/mysql/direct.php',
            '_core/service/entity/descriptor/mysql/schema.php',
            '_core/service/entity/designer.php',
            '_core/service/entity/designer/delete.php',
            '_core/service/entity/designer/insert.php',
            '_core/service/entity/designer/select.php',
            '_core/service/entity/designer/snippety.php',
            '_core/service/entity/designer/update.php',
            '_core/service/entity/encapsulant/simple.php',
            '_core/service/entity/snippet.php',
            '_core/service/error.php',
            '_core/service/file_system.php',
            '_core/service/form.php',
            '_core/service/form/validator/base.php',
            '_core/service/form/validator/common.php',
            '_core/service/form/validator/date.php',
            '_core/service/form/validator/number.php',
            '_core/service/form/validator/phone.php',
            '_core/service/form/validator/select.php',
            '_core/service/form/validator/string.php',
            '_core/service/form/validator/string_validator.php',
            '_core/service/form/validator/upload.php',
            '_core/service/form/validator/uri.php',
            '_core/service/header.php',
            '_core/service/header/code.php',
            '_core/service/image_draw.php',
            '_core/service/image_modify.php',
            '_core/service/json.php',
            '_core/service/locale.php',
            '_core/service/log.php',
            '_core/service/log/parser_base.php',
            '_core/service/log/parser_bootstrap.php',
            '_core/service/log/parser_data.php',
            '_core/service/log/parser_error.php',
            '_core/service/log/parser_message.php',
            '_core/service/matcher.php',
            '_core/service/matcher/item.php',
            '_core/service/matcher/item/base.php',
            '_core/service/matcher/item/cli.php',
            '_core/service/matcher/item/handler.php',
            '_core/service/matcher/item/parsed.php',
            '_core/service/matcher/item/source.php',
            '_core/service/matcher/item/uri.php',
            '_core/service/matcher/stack.php',
            '_core/service/obfuscator.php',
            '_core/service/obfuscator/base.php',
            '_core/service/obfuscator/simple.php',
            '_core/service/pager.php',
            '_core/service/plain.php',
            '_core/service/reflector.php',
            '_core/service/request.php',
            '_core/service/rest.php',
            '_core/service/role.php',
            '_core/service/session.php',
            '_core/service/session/adodb.php',
            '_core/service/session/inbuilt.php',
            '_core/service/session/pear.php',
            '_core/service/soap.php',
            '_core/service/tab.php',
            '_core/service/tab/delegate.php',
            '_core/service/tab/delegate/urlMaker.php',
            '_core/service/tab/engine.php',
            '_core/service/tab/subscriber.php',
            '_core/service/template.php',
            '_core/service/template/parser/base.php',
            '_core/service/template/parser/form.php',
            '_core/service/template/parser/image.php',
            '_core/service/template/parser/main.php',
            '_core/service/template/type/base.php',
            '_core/service/template/type/form.php',
            '_core/service/template/type/image.php',
            '_core/service/timer.php',
            '_core/service/translation.php',
            '_core/service/user.php',
            '_core/service/user/base.php',
            '_core/service/user/config.php',
            '_core/service/user/entity.php',
            '_core/view/definer.php',
            '_core/view/keeper.php',
            '_core/view/keeper/loader/json.php',
            '_core/view/keeper/loader/text.php',
            '_core/view/parser.php',
            '_core/view/parser/debug1.php',
            '_core/view/parser/debug2.php',
            '_core/view/parser/html.php',
            '_core/view/parser/json.php',
            '_core/view/parser/loader.php',
            '_core/view/parser/soap.php',
            '_core/view/parser/xml.php',
            '_core/view/router.php',
            '_core/view/router/html.php',
            '_core/view/router/json.php',
            '_core/view/router/loader.php',
            '_core/view/router/simple.php'
        ];
    }

    private function getCreatedTests(): array
    {
        return [
            '_core/base/data.php' => 'unit/_core/base/DataTest.php',
            '_core/base/meta/delayed.php' => 'unit/_core/base/meta/DelayedTest.php',
            '_core/base/meta/maker.php' => 'unit/_core/base/meta/MakerTest.php',
            '_core/base/meta/row.php' => 'unit/_core/base/meta/RowTest.php',
            '_core/base/model/entity.php' => 'unit/_core/base/model/EntityTest.php',
            '_core/base/model/file_data/entity.php' => 'unit/_core/base/model/file_data/EntityTest.php',
            '_core/base/model/file_data/row.php' => 'unit/_core/base/model/file_data/RowTest.php',
            '_core/base/model/request.php' => 'unit/_core/base/model/RequestTest.php',
            '_core/base/model/row.php' => 'unit/_core/base/model/RowTest.php',
            '_core/base/model/rowset.php' => 'unit/_core/base/model/RowsetTest.php',
            '_core/base/model/spec_file/entity.php' => 'unit/_core/base/model/spec_file/EntityTest.php',
            '_core/base/model/spec_file/image/entity.php' => 'unit/_core/base/model/spec_file/image/EntityTest.php',
            '_core/base/model/spec_file/image/row.php' => 'unit/_core/base/model/spec_file/image/RowTest.php',
            '_core/base/model/spec_file/row.php' => 'unit/_core/base/model/spec_file/RowTest.php',
            '_core/base/service.php' => 'unit/_core/base/ServiceTest.php',
            '_core/base/service/multi.php' => 'unit/_core/base/service/MultiTest.php',
            '_core/base/service/single.php' => 'unit/_core/base/service/SingleTest.php',
            '_core/base/timer_program.php' => 'unit/_core/base/TimerProgramTest.php',
            '_core/base/transfer.php' => 'unit/_core/base/TransferTest.php',
            '_core/base/transfer/int.php' => 'unit/_core/base/transfer/IntTest.php',
            '_core/base/transfer/out.php' => 'unit/_core/base/transfer/OutTest.php',
            '_core/base/transfer/sham.php' => 'unit/_core/base/transfer/ShamTest.php',
            '_core/base/transfer/transfer_int.php' => 'unit/_core/base/transfer/TransferIntTest.php',
            '_core/block/admin/base.php' => 'unit/_core/block/admin/BaseTest.php',
            '_core/block/admin/data.php' => 'unit/_core/block/admin/DataTest.php',
            '_core/block/admin/data_form.php' => 'unit/_core/block/admin/DataFormTest.php',
            '_core/block/admin/data_info.php' => 'unit/_core/block/admin/DataInfoTest.php',
            '_core/block/admin/data_table.php' => 'unit/_core/block/admin/DataTableTest.php',
            '_core/block/admin/form_pattern.php' => 'unit/_core/block/admin/FormPatternTest.php',
            '_core/block/admin/index.php' => 'unit/_core/block/admin/IndexTest.php',
            '_core/block/admin/root.php' => 'unit/_core/block/admin/RootTest.php',
            '_core/block/admin/select_dependent.php' => 'unit/_core/block/admin/SelectDependentTest.php',
            '_core/block/admin/structure.php' => 'unit/_core/block/admin/StructureTest.php',
            '_core/block/admin/upload_file.php' => 'unit/_core/block/admin/UploadFileTest.php',
            '_core/block/admin/upload_flash.php' => 'unit/_core/block/admin/UploadFlashTest.php',
            '_core/block/admin/upload_image.php' => 'unit/_core/block/admin/UploadImageTest.php',
            '_core/block/base.php' => 'unit/_core/block/BaseTest.php',
            '_core/block/common/html_nav.php' => 'unit/_core/block/common/HtmlNavTest.php',
            '_core/block/common/html_nav_db.php' => 'unit/_core/block/common/HtmlNavDbTest.php',
            '_core/block/common/html_pager.php' => 'unit/_core/block/common/HtmlPagerTest.php',
            '_core/block/common/html_pager_quantifier.php' => 'unit/_core/block/common/HtmlPagerQuantifierTest.php',
            '_core/block/common/simple.php' => 'unit/_core/block/common/SimpleTest.php',
            '_core/block/error/error403.php' => 'unit/_core/block/error/Error403Test.php',
            '_core/block/error/error404.php' => 'unit/_core/block/error/Error404Test.php',
            '_core/block/error/error500.php' => 'unit/_core/block/error/Error500Test.php',
            '_core/block/form/parser.php' => 'unit/_core/block/form/ParserTest.php',
            '_core/block/form/part.php' => 'unit/_core/block/form/PartTest.php',
            '_core/block/form/usual.php' => 'unit/_core/block/form/UsualTest.php',
            '_core/block/loader/base.php' => 'unit/_core/block/loader/BaseTest.php',
            '_core/block/loader/loader_form_validation.php' => 'unit/_core/block/loader/LoaderFormValidationTest.php',
            '_core/block/root/html.php' => 'unit/_core/block/root/HtmlTest.php',
            '_core/cli/restore_password.php' => 'unit/_core/cli/RestorePasswordTest.php',
            '_core/error/demonstrator.php' => 'unit/_core/error/DemonstratorTest.php',
            '_core/exception/base.php' => 'unit/_core/exception/BaseTest.php',
            '_core/exception/block/fatal.php' => 'unit/_core/exception/block/FatalTest.php',
            '_core/exception/block/form_part.php' => 'unit/_core/exception/block/FormPartTest.php',
            '_core/exception/block/local.php' => 'unit/_core/exception/block/LocalTest.php',
            '_core/exception/error500.php' => 'unit/_core/exception/Error500Test.php',
            '_core/exception/fatal.php' => 'unit/_core/exception/FatalTest.php',
            '_core/exception/model/entity/fatal.php' => 'unit/_core/exception/model/entity/FatalTest.php',
            '_core/exception/model/reverse.php' => 'unit/_core/exception/model/ReverseTest.php',
            '_core/exception/plain/fatal.php' => 'unit/_core/exception/plain/FatalTest.php',
            '_core/exception/service/database.php' => 'unit/_core/exception/service/DatabaseTest.php',
            '_core/exception/service/date.php' => 'unit/_core/exception/service/DateTest.php',
            '_core/exception/service/fatal.php' => 'unit/_core/exception/service/FatalTest.php',
            '_core/exception/template/fatal.php' => 'unit/_core/exception/template/FatalTest.php',
            '_core/functions.php' => 'unit/_core/FunctionsTest.php',
            '_core/plain/captcha.php' => 'unit/_core/plain/CaptchaTest.php',
            '_core/plain/db_file.php' => 'unit/_core/plain/DbFileTest.php',
            '_core/plain/image.php' => 'unit/_core/plain/ImageTest.php',
            '_core/plain/obfuscator.php' => 'unit/_core/plain/ObfuscatorTest.php',
            '_core/plain/video.php' => 'unit/_core/plain/VideoTest.php',
            '_core/service/application.php' => 'unit/_core/service/ApplicationTest.php',
            '_core/service/cache.php' => 'unit/_core/service/CacheTest.php',
            '_core/service/cache/base.php' => 'unit/_core/service/cache/BaseTest.php',
            '_core/service/cache/file.php' => 'unit/_core/service/cache/FileTest.php',
            '_core/service/cache/memcache.php' => 'unit/_core/service/cache/MemcacheTest.php',
            '_core/service/cache/memcached.php' => 'unit/_core/service/cache/MemcachedTest.php',
            '_core/service/cache/wrapper/file_data.php' => 'unit/_core/service/cache/wrapper/FileDataTest.php',
            '_core/service/captcha.php' => 'unit/_core/service/CaptchaTest.php',
            '_core/service/captcha/base.php' => 'unit/_core/service/captcha/BaseTest.php',
            '_core/service/captcha/file_maker/picture_1.php' => 'unit/_core/service/captcha/file_maker/Picture1Test.php',
            '_core/service/captcha/text_generator/simple.php' => 'unit/_core/service/captcha/text_generator/SimpleTest.php',
            '_core/service/cli.php' => 'unit/_core/service/CliTest.php',
            '_core/service/config.php' => 'unit/_core/service/ConfigTest.php',
            '_core/service/config/arr.php' => 'unit/_core/service/config/ArrTest.php',
            '_core/service/config/base.php' => 'unit/_core/service/config/BaseTest.php',
            '_core/service/config/ini.php' => 'unit/_core/service/config/IniTest.php',
            '_core/service/config/row.php' => 'unit/_core/service/config/RowTest.php',
            '_core/service/config/xml.php' => 'unit/_core/service/config/XmlTest.php',
            '_core/service/config/yaml.php' => 'unit/_core/service/config/YamlTest.php',
            '_core/service/cookie.php' => 'unit/_core/service/CookieTest.php',
            '_core/service/curl.php' => 'unit/_core/service/CurlTest.php',
            '_core/service/database.php' => 'unit/_core/service/DatabaseTest.php',
            '_core/service/database/adodb.php' => 'unit/_core/service/database/AdodbTest.php',
            '_core/service/database/base.php' => 'unit/_core/service/database/BaseTest.php',
            '_core/service/database/mysql.php' => 'unit/_core/service/database/MysqlTest.php',
            '_core/service/database/mysqlImproved.php' => 'unit/_core/service/database/MysqlImprovedTest.php',
            '_core/service/database/mysqlPdo.php' => 'unit/_core/service/database/MysqlPdoTest.php',
            '_core/service/date.php' => 'unit/_core/service/DateTest.php',
            '_core/service/debug.php' => 'unit/_core/service/DebugTest.php',
            '_core/service/email.php' => 'unit/_core/service/EmailTest.php',
            '_core/service/email/phpmailer.php' => 'unit/_core/service/email/PhpmailerTest.php',
            '_core/service/entity.php' => 'unit/_core/service/EntityTest.php',
            '_core/service/entity/description.php' => 'unit/_core/service/entity/DescriptionTest.php',
            '_core/service/entity/descriptor.php' => 'unit/_core/service/entity/DescriptorTest.php',
            '_core/service/entity/descriptor/mysql.php' => 'unit/_core/service/entity/descriptor/MysqlTest.php',
            '_core/service/entity/descriptor/mysql/direct.php' => 'unit/_core/service/entity/descriptor/mysql/DirectTest.php',
            '_core/service/entity/descriptor/mysql/schema.php' => 'unit/_core/service/entity/descriptor/mysql/SchemaTest.php',
            '_core/service/entity/designer.php' => 'unit/_core/service/entity/DesignerTest.php',
            '_core/service/entity/designer/delete.php' => 'unit/_core/service/entity/designer/DeleteTest.php',
            '_core/service/entity/designer/insert.php' => 'unit/_core/service/entity/designer/InsertTest.php',
            '_core/service/entity/designer/select.php' => 'unit/_core/service/entity/designer/SelectTest.php',
            '_core/service/entity/designer/snippety.php' => 'unit/_core/service/entity/designer/SnippetyTest.php',
            '_core/service/entity/designer/update.php' => 'unit/_core/service/entity/designer/UpdateTest.php',
            '_core/service/entity/encapsulant/simple.php' => 'unit/_core/service/entity/encapsulant/SimpleTest.php',
            '_core/service/entity/snippet.php' => 'unit/_core/service/entity/SnippetTest.php',
            '_core/service/error.php' => 'unit/_core/service/ErrorTest.php',
            '_core/service/file_system.php' => 'unit/_core/service/FileSystemTest.php',
            '_core/service/form.php' => 'unit/_core/service/FormTest.php',
            '_core/service/form/validator/base.php' => 'unit/_core/service/form/validator/BaseTest.php',
            '_core/service/form/validator/common.php' => 'unit/_core/service/form/validator/CommonTest.php',
            '_core/service/form/validator/date.php' => 'unit/_core/service/form/validator/DateTest.php',
            '_core/service/form/validator/number.php' => 'unit/_core/service/form/validator/NumberTest.php',
            '_core/service/form/validator/phone.php' => 'unit/_core/service/form/validator/PhoneTest.php',
            '_core/service/form/validator/select.php' => 'unit/_core/service/form/validator/SelectTest.php',
            '_core/service/form/validator/string.php' => 'unit/_core/service/form/validator/StringTest.php',
            '_core/service/form/validator/string_validator.php' => 'unit/_core/service/form/validator/StringValidatorTest.php',
            '_core/service/form/validator/upload.php' => 'unit/_core/service/form/validator/UploadTest.php',
            '_core/service/form/validator/uri.php' => 'unit/_core/service/form/validator/UriTest.php',
            '_core/service/header.php' => 'unit/_core/service/HeaderTest.php',
            '_core/service/header/code.php' => 'unit/_core/service/header/CodeTest.php',
            '_core/service/image_draw.php' => 'unit/_core/service/ImageDrawTest.php',
            '_core/service/image_modify.php' => 'unit/_core/service/ImageModifyTest.php',
            '_core/service/json.php' => 'unit/_core/service/JsonTest.php',
            '_core/service/locale.php' => 'unit/_core/service/LocaleTest.php',
            '_core/service/log.php' => 'unit/_core/service/LogTest.php',
            '_core/service/log/parser_base.php' => 'unit/_core/service/log/ParserBaseTest.php',
            '_core/service/log/parser_bootstrap.php' => 'unit/_core/service/log/ParserBootstrapTest.php',
            '_core/service/log/parser_data.php' => 'unit/_core/service/log/ParserDataTest.php',
            '_core/service/log/parser_error.php' => 'unit/_core/service/log/ParserErrorTest.php',
            '_core/service/log/parser_message.php' => 'unit/_core/service/log/ParserMessageTest.php',
            '_core/service/matcher.php' => 'unit/_core/service/MatcherTest.php',
            '_core/service/matcher/item.php' => 'unit/_core/service/matcher/ItemTest.php',
            '_core/service/matcher/item/base.php' => 'unit/_core/service/matcher/item/BaseTest.php',
            '_core/service/matcher/item/cli.php' => 'unit/_core/service/matcher/item/CliTest.php',
            '_core/service/matcher/item/handler.php' => 'unit/_core/service/matcher/item/HandlerTest.php',
            '_core/service/matcher/item/parsed.php' => 'unit/_core/service/matcher/item/ParsedTest.php',
            '_core/service/matcher/item/source.php' => 'unit/_core/service/matcher/item/SourceTest.php',
            '_core/service/matcher/item/uri.php' => 'unit/_core/service/matcher/item/UriTest.php',
            '_core/service/matcher/stack.php' => 'unit/_core/service/matcher/StackTest.php',
            '_core/service/obfuscator.php' => 'unit/_core/service/ObfuscatorTest.php',
            '_core/service/obfuscator/base.php' => 'unit/_core/service/obfuscator/BaseTest.php',
            '_core/service/obfuscator/simple.php' => 'unit/_core/service/obfuscator/SimpleTest.php',
            '_core/service/pager.php' => 'unit/_core/service/PagerTest.php',
            '_core/service/plain.php' => 'unit/_core/service/PlainTest.php',
            '_core/service/reflector.php' => 'unit/_core/service/ReflectorTest.php',
            '_core/service/request.php' => 'unit/_core/service/RequestTest.php',
            '_core/service/rest.php' => 'unit/_core/service/RestTest.php',
            '_core/service/role.php' => 'unit/_core/service/RoleTest.php',
            '_core/service/session.php' => 'unit/_core/service/SessionTest.php',
            '_core/service/session/adodb.php' => 'unit/_core/service/session/AdodbTest.php',
            '_core/service/session/inbuilt.php' => 'unit/_core/service/session/InbuiltTest.php',
            '_core/service/session/pear.php' => 'unit/_core/service/session/PearTest.php',
            '_core/service/soap.php' => 'unit/_core/service/SoapTest.php',
            '_core/service/tab.php' => 'unit/_core/service/TabTest.php',
            '_core/service/tab/delegate.php' => 'unit/_core/service/tab/DelegateTest.php',
            '_core/service/tab/delegate/urlMaker.php' => 'unit/_core/service/tab/delegate/UrlMakerTest.php',
            '_core/service/tab/engine.php' => 'unit/_core/service/tab/EngineTest.php',
            '_core/service/tab/subscriber.php' => 'unit/_core/service/tab/SubscriberTest.php',
            '_core/service/template.php' => 'unit/_core/service/TemplateTest.php',
            '_core/service/template/parser/base.php' => 'unit/_core/service/template/parser/BaseTest.php',
            '_core/service/template/parser/form.php' => 'unit/_core/service/template/parser/FormTest.php',
            '_core/service/template/parser/image.php' => 'unit/_core/service/template/parser/ImageTest.php',
            '_core/service/template/parser/main.php' => 'unit/_core/service/template/parser/MainTest.php',
            '_core/service/template/type/base.php' => 'unit/_core/service/template/type/BaseTest.php',
            '_core/service/template/type/form.php' => 'unit/_core/service/template/type/FormTest.php',
            '_core/service/template/type/image.php' => 'unit/_core/service/template/type/ImageTest.php',
            '_core/service/timer.php' => 'unit/_core/service/TimerTest.php',
            '_core/service/translation.php' => 'unit/_core/service/TranslationTest.php',
            '_core/service/user.php' => 'unit/_core/service/UserTest.php',
            '_core/service/user/base.php' => 'unit/_core/service/user/BaseTest.php',
            '_core/service/user/config.php' => 'unit/_core/service/user/ConfigTest.php',
            '_core/service/user/entity.php' => 'unit/_core/service/user/EntityTest.php',
            '_core/view/definer.php' => 'unit/_core/view/DefinerTest.php',
            '_core/view/keeper.php' => 'unit/_core/view/KeeperTest.php',
            '_core/view/keeper/loader/json.php' => 'unit/_core/view/keeper/loader/JsonTest.php',
            '_core/view/keeper/loader/text.php' => 'unit/_core/view/keeper/loader/TextTest.php',
            '_core/view/parser.php' => 'unit/_core/view/ParserTest.php',
            '_core/view/parser/debug1.php' => 'unit/_core/view/parser/Debug1Test.php',
            '_core/view/parser/debug2.php' => 'unit/_core/view/parser/Debug2Test.php',
            '_core/view/parser/html.php' => 'unit/_core/view/parser/HtmlTest.php',
            '_core/view/parser/json.php' => 'unit/_core/view/parser/JsonTest.php',
            '_core/view/parser/loader.php' => 'unit/_core/view/parser/LoaderTest.php',
            '_core/view/parser/soap.php' => 'unit/_core/view/parser/SoapTest.php',
            '_core/view/parser/xml.php' => 'unit/_core/view/parser/XmlTest.php',
            '_core/view/router.php' => 'unit/_core/view/RouterTest.php',
            '_core/view/router/html.php' => 'unit/_core/view/router/HtmlTest.php',
            '_core/view/router/json.php' => 'unit/_core/view/router/JsonTest.php',
            '_core/view/router/loader.php' => 'unit/_core/view/router/LoaderTest.php',
            '_core/view/router/simple.php' => 'unit/_core/view/router/SimpleTest.php'
        ];
    }

    private function getSkippedSourceFiles(): array
    {
        return [
            '_core/block/admin/data.meta.php' => 'metadata array/configuration file; no executable unit behavior beyond framework loading',
            '_core/block/admin/data_form.meta.php' => 'metadata array/configuration file; no executable unit behavior beyond framework loading',
            '_core/block/admin/data_info.meta.php' => 'metadata array/configuration file; no executable unit behavior beyond framework loading',
            '_core/block/admin/data_table.meta.php' => 'metadata array/configuration file; no executable unit behavior beyond framework loading',
            '_core/block/admin/form_pattern.meta.php' => 'metadata array/configuration file; no executable unit behavior beyond framework loading',
            '_core/block/admin/index.meta.php' => 'metadata array/configuration file; no executable unit behavior beyond framework loading',
            '_core/block/admin/root.meta.php' => 'metadata array/configuration file; no executable unit behavior beyond framework loading',
            '_core/block/admin/structure.meta.php' => 'metadata array/configuration file; no executable unit behavior beyond framework loading',
            '_core/block/common/html_pager.meta.php' => 'metadata array/configuration file; no executable unit behavior beyond framework loading',
            '_core/block/common/html_pager_quantifier.meta.php' => 'metadata array/configuration file; no executable unit behavior beyond framework loading',
            '_core/block/form/parser.meta.php' => 'metadata array/configuration file; no executable unit behavior beyond framework loading',
            '_core/block/form/usual.meta.php' => 'metadata array/configuration file; no executable unit behavior beyond framework loading',
            '_core/block/root/html.meta.php' => 'metadata array/configuration file; no executable unit behavior beyond framework loading',
            '_core/bootstrap.php' => 'bootstrap/runtime wiring file with global side effects; integration/bootstrap coverage is safer than isolated unit loading',
            '_core/bootstrap/initializer.php' => 'bootstrap/runtime wiring file with global side effects; integration/bootstrap coverage is safer than isolated unit loading',
            '_core/bootstrap/loader.php' => 'bootstrap/runtime wiring file with global side effects; integration/bootstrap coverage is safer than isolated unit loading',
            '_core/bootstrap/runner.php' => 'bootstrap/runtime wiring file with global side effects; integration/bootstrap coverage is safer than isolated unit loading',
            '_core/error/template/default.php' => 'presentation template fragment; behavior belongs to renderer/error service integration',
            '_core/error/template/error_403.php' => 'presentation template fragment; behavior belongs to renderer/error service integration',
            '_core/error/template/error_404.php' => 'presentation template fragment; behavior belongs to renderer/error service integration',
            '_core/error/template/error_500.php' => 'presentation template fragment; behavior belongs to renderer/error service integration',
            '_core/ini_cli.php' => 'bootstrap/runtime wiring file with global side effects; integration/bootstrap coverage is safer than isolated unit loading'
        ];
    }

    public function testEveryCorePhpSourceFileIsClassified(): void
    {
        $classified = array_merge(array_keys($this->getCreatedTests()), array_keys($this->getSkippedSourceFiles()));
        sort($classified);
        $discovered = $this->getDiscoveredSourceFiles();
        sort($discovered);
        $this->assertSame($discovered, $classified);
    }

    public function testCreatedTestFilesExistInPreservedUnitTree(): void
    {
        $root = dirname(dirname(__DIR__));
        foreach ($this->getCreatedTests() as $source => $test) {
            $this->assertSame(0, strpos($test, 'unit/'), $source);
            $this->assertFileExists($root . '/' . $test, $source);
        }
    }

    public function testSkippedFilesHaveExplicitReasons(): void
    {
        foreach ($this->getSkippedSourceFiles() as $source => $reason) {
            $this->assertNotEmpty($reason, $source);
        }
    }
}
