<?php

declare(strict_types=1);

namespace fan\core\di;

final class application_service_graph_registration_context
{
    public function __construct(
        public application_core_service_creator $coreServiceCreator,
        public application_content_service_creator $contentServiceCreator,
        public application_navigation_service_creator $navigationServiceCreator,
        public application_controller_service_creator $controllerServiceCreator,
        public application_infrastructure_service_creator $infrastructureServiceCreator,
        public application_client_service_creator $clientServiceCreator,
        public application_pager_service_creator $pagerServiceCreator,
        public application_utility_service_creator $utilityServiceCreator,
        public application_session_service_creator $sessionServiceCreator,
        public application_user_service_creator $userServiceCreator,
        public \Closure $configServiceFactory,
        public \Closure $cacheEngineFactory,
        public \Closure $cacheServiceFactory,
        public \Closure $requestServiceFactory,
        public \Closure $sessionServiceFactory,
        public \Closure $sessionEngineFactory,
        public \Closure $roleServiceFactory,
        public \Closure $entityDesignerFactory,
        public \Closure $entityEncapsulantFactory,
        public \Closure $modelEntityFactory,
        public \Closure $modelRowFactory,
        public \Closure $modelRowsetFactory,
        public \Closure $modelRequestFactory,
        public \Closure $tabDelegateFactory,
        public \Closure $tabViewParserFactory,
        public \Closure $tabServiceFactory,
        public \Closure $jsonServiceFactory,
        public \Closure $errorServiceFactory,
        public \Closure $headerServiceFactory,
        public \Closure $localeServiceFactory,
        public \Closure $applicationServiceFactory,
        public \Closure $blockFactory,
        public \Closure $matcherItemFactory,
        public \Closure $matcherItemComponentFactory,
        public \Closure $matcherServiceFactory,
        public \Closure $reflectorServiceFactory,
        public \Closure $translationServiceFactory,
        public \Closure $debugServiceFactory,
        public \Closure $plainControllerFactory,
        public \Closure $plainServiceFactory,
        public \Closure $timerProgramFactory,
        public \Closure $timerServiceFactory,
        public \Closure $dateServiceFactory,
        public \Closure $cookieServiceFactory,
        public \Closure $curlServiceFactory,
        public \Closure $restServiceFactory,
        public \Closure $pagerServiceFactory,
        public \Closure $obfuscatorServiceFactory,
        public \Closure $imageModifyServiceFactory,
        public \Closure $soapServiceFactory,
        public \Closure $fileSystemServiceFactory,
        public \Closure $userServiceFactory,
        public \Closure $userEngineFactory
    ) {
    }

    public static function fromBundles(
        application_container_dependency_bundle $dependencyBundle,
        application_service_factory_bundle $factoryBundle,
        callable $cacheEngineFactory,
        callable $sessionEngineFactory,
        callable $userEngineFactory,
        callable $modelRowFactory,
        callable $modelRowsetFactory
    ): self {
        return new self(
            $dependencyBundle->coreServiceCreator,
            $dependencyBundle->contentServiceCreator,
            $dependencyBundle->navigationServiceCreator,
            $dependencyBundle->controllerServiceCreator,
            $dependencyBundle->infrastructureServiceCreator,
            $dependencyBundle->clientServiceCreator,
            $dependencyBundle->pagerServiceCreator,
            $dependencyBundle->utilityServiceCreator,
            $dependencyBundle->sessionServiceCreator,
            $dependencyBundle->userServiceCreator,
            $factoryBundle->configServiceFactory,
            \Closure::fromCallable($cacheEngineFactory),
            $factoryBundle->cacheServiceFactory,
            $factoryBundle->requestServiceFactory,
            $factoryBundle->sessionServiceFactory,
            \Closure::fromCallable($sessionEngineFactory),
            $factoryBundle->roleServiceFactory,
            $factoryBundle->entityDesignerFactory,
            $factoryBundle->entityEncapsulantFactory,
            $factoryBundle->modelEntityFactory,
            \Closure::fromCallable($modelRowFactory),
            \Closure::fromCallable($modelRowsetFactory),
            $factoryBundle->modelRequestFactory,
            $factoryBundle->tabDelegateFactory,
            $factoryBundle->tabViewParserFactory,
            $factoryBundle->tabServiceFactory,
            $factoryBundle->jsonServiceFactory,
            $factoryBundle->errorServiceFactory,
            $factoryBundle->headerServiceFactory,
            $factoryBundle->localeServiceFactory,
            $factoryBundle->applicationServiceFactory,
            $factoryBundle->blockFactory,
            $factoryBundle->matcherItemFactory,
            $factoryBundle->matcherItemComponentFactory,
            $factoryBundle->matcherServiceFactory,
            $factoryBundle->reflectorServiceFactory,
            $factoryBundle->translationServiceFactory,
            $factoryBundle->debugServiceFactory,
            $factoryBundle->plainControllerFactory,
            $factoryBundle->plainServiceFactory,
            $factoryBundle->timerProgramFactory,
            $factoryBundle->timerServiceFactory,
            $factoryBundle->dateServiceFactory,
            $factoryBundle->cookieServiceFactory,
            $factoryBundle->curlServiceFactory,
            $factoryBundle->restServiceFactory,
            $factoryBundle->pagerServiceFactory,
            $factoryBundle->obfuscatorServiceFactory,
            $factoryBundle->imageModifyServiceFactory,
            $factoryBundle->soapServiceFactory,
            $factoryBundle->fileSystemServiceFactory,
            $factoryBundle->userServiceFactory,
            \Closure::fromCallable($userEngineFactory)
        );
    }
}
