<?php

declare(strict_types=1);
use PHPUnit\Framework\TestCase;


class CoreSourceInventoryTest extends TestCase
{
    private function getDiscoveredSourceFiles(): array
    {
        return [
            'core/base/data.php',
            'core/base/meta/delayed.php',
            'core/base/meta/maker.php',
            'core/base/meta/maker_state.php',
            'core/base/meta/row.php',
            'core/base/model/entity.php',
            'core/base/model/entity_dependencies.php',
            'core/base/model/file_data/entity.php',
            'core/base/model/file_data/row.php',
            'core/base/model/request.php',
            'core/base/model/row.php',
            'core/base/model/rowset.php',
            'core/base/model/spec_file/entity.php',
            'core/base/model/spec_file/image/entity.php',
            'core/base/model/spec_file/image/row.php',
            'core/base/model/spec_file/image/row_state.php',
            'core/base/model/spec_file/row.php',
            'core/base/service.php',
            'core/base/service/multi.php',
            'core/base/service/single.php',
            'core/base/timer_program.php',
            'core/base/transfer.php',
            'core/base/transfer/int.php',
            'core/base/transfer/out.php',
            'core/base/transfer/sham.php',
            'core/base/transfer/transfer_int.php',
            'core/block/admin/base.php',
            'core/block/admin/data.meta.php',
            'core/block/admin/data.php',
            'core/block/admin/data_form.meta.php',
            'core/block/admin/data_form.php',
            'core/block/admin/data_info.meta.php',
            'core/block/admin/data_info.php',
            'core/block/admin/data_table.meta.php',
            'core/block/admin/data_table.php',
            'core/block/admin/form_pattern.meta.php',
            'core/block/admin/form_pattern.php',
            'core/block/admin/index.meta.php',
            'core/block/admin/index.php',
            'core/block/admin/root.meta.php',
            'core/block/admin/root.php',
            'core/block/admin/select_dependent.php',
            'core/block/admin/structure.meta.php',
            'core/block/admin/structure.php',
            'core/block/admin/upload_file.php',
            'core/block/admin/upload_image.php',
            'core/block/base.php',
            'core/block/base_dependency_defaults.php',
            'core/block/common/html_nav.php',
            'core/block/common/html_nav_db.php',
            'core/block/common/html_pager.meta.php',
            'core/block/common/html_pager.php',
            'core/block/common/simple.php',
            'core/block/error/error403.php',
            'core/block/error/error404.php',
            'core/block/error/error500.php',
            'core/block/loader/base.php',
            'core/block/loader/loader_form_validation.php',
            'core/block/root/html.meta.php',
            'core/block/root/html.php',
            'core/application/application.php',
            'core/factory/application_container_defaults_factory.php',
            'core/factory/application_container_defaults_provider_factory.php',
            'core/factory/application_container_creator_defaults_provider_factory.php',
            'core/factory/application_container_factory_callable_factory.php',
            'core/factory/application_container_factory_provider_defaults_provider_factory.php',
            'core/factory/application_container_operations_defaults_provider_factory.php',
            'core/factory/application_container_registrar_defaults_provider_factory.php',
            'core/factory/application_container_registry_defaults_provider_factory.php',
            'core/factory/application_defaults_factory.php',
            'core/factory/application_runtime_class_instantiator_provider.php',
            'core/factory/application_runtime_configured_service_provider.php',
            'core/factory/bootstrap_object_defaults_factory.php',
            'core/factory/bootstrap_object_class_instantiator_provider.php',
            'core/factory/bootstrap_object_configured_service_provider.php',
            'core/factory/bootstrap_object_defaults_provider_factory.php',
            'core/factory/bootstrap_object_factory.php',
            'core/factory/bootstrap_request_input_defaults_factory.php',
            'core/factory/bootstrap_runtime_defaults_factory.php',
            'core/factory/bootstrap_runtime_factory.php',
            'core/factory/bootstrap_runtime_operations_defaults_provider_factory.php',
            'core/factory/bootstrap_runtime_service_defaults_factory.php',
            'core/factory/bootstrap_runtime_service_factory_defaults_provider_factory.php',
            'core/factory/bootstrap_runtime_service_defaults_provider_factory.php',
            'core/factory/bootstrap_runtime_state_defaults_factory.php',
            'core/factory/bootstrap_runtime_state_factory_defaults_provider_factory.php',
            'core/factory/bootstrap_runtime_state_defaults_provider_factory.php',
            'core/application/context_bootstrap_operations.php',
            'core/factory/context_container_defaults_factory.php',
            'core/factory/context_core_defaults_factory.php',
            'core/factory/context_core_defaults_provider_factory.php',
            'core/factory/context_defaults_factory.php',
            'core/factory/context_support_defaults_factory.php',
            'core/factory/context_support_defaults_provider_factory.php',
            'core/factory/runtime/error_handling_defaults_factory.php',
            'core/factory/runtime/error_logger_defaults_factory.php',
            'core/factory/error_logger_defaults_provider_factory.php',
            'core/application/initializer.php',
            'core/application/loader.php',
            'core/application/request_runner.php',
            'core/factory/request_runner_defaults_factory.php',
            'core/application/web_application_initializer.php',
            'core/factory/web_application_initializer_defaults_factory.php',
            'core/factory/runtime/request_input_defaults_factory.php',
            'core/factory/adapter/request_input_globals_factory.php',
            'core/factory/runtime/request_input_factory.php',
            'core/factory/runtime/request_input_source_defaults_factory.php',
            'core/factory/request_input_source_defaults_provider_factory.php',
            'core/factory/runtime/request_input_source_factory.php',
            'core/application/runner.php',
            'core/error/demonstrator.php',
            'core/error/template/default.php',
            'core/error/template/error_403.php',
            'core/error/template/error_404.php',
            'core/error/template/error_500.php',
            'core/exception/base.php',
            'core/exception/block/fatal.php',
            'core/exception/block/local.php',
            'core/exception/error500.php',
            'core/exception/fatal.php',
            'core/exception/model/reverse.php',
            'core/exception/plain/fatal.php',
            'core/exception/service/date.php',
            'core/exception/service/fatal.php',
            'core/functions.php',
            'core/plain/db_file.php',
            'core/plain/image.php',
            'core/plain/obfuscator.php',
            'core/service/application.php',
            'core/service/block_context.php',
            'core/service/bootstrap_runtime.php',
            'core/service/cache.php',
            'core/service/cache_memcache_state.php',
            'core/service/cache_state.php',
            'core/service/cache/base.php',
            'core/service/cache/file.php',
            'core/service/cache/memcache.php',
            'core/service/cache/memcached.php',
            'core/service/cache/wrapper/file_data.php',
            'core/service/config.php',
            'core/service/config_state.php',
            'core/service/config/arr.php',
            'core/service/config/base.php',
            'core/service/config/row.php',
            'core/service/config/xml.php',
            'core/service/config/yaml.php',
            'core/service/cookie.php',
            'core/service/cookie_state.php',
            'core/service/curl.php',
            'core/service/curl_state.php',
            'core/service/date.php',
            'core/service/date_state.php',
            'core/service/debug.php',
            'core/service/error.php',
            'core/service/file_system.php',
            'core/service/file_system_state.php',
            'core/service/header.php',
            'core/service/header/code.php',
            'core/service/image_draw.php',
            'core/service/image_modify.php',
            'core/service/image_modify_state.php',
            'core/service/json.php',
            'core/service/json_state.php',
            'core/service/locale.php',
            'core/service/matcher.php',
            'core/service/matcher/item.php',
            'core/service/matcher/item/base.php',
            'core/service/matcher/item/handler.php',
            'core/service/matcher/item/parsed.php',
            'core/service/matcher/item/source.php',
            'core/service/matcher/item/uri.php',
            'core/service/matcher/stack.php',
            'core/service/obfuscator.php',
            'core/service/obfuscator_state.php',
            'core/service/obfuscator/base.php',
            'core/service/obfuscator/simple.php',
            'core/service/pager.php',
            'core/service/pager_state.php',
            'core/service/plain.php',
            'core/service/plain_file_context.php',
            'core/service/reflector.php',
            'core/service/request.php',
            'core/service/request_input.php',
            'core/service/request_input_source.php',
            'core/service/rest.php',
            'core/service/rest_state.php',
            'core/service/role.php',
            'core/service/service_listener_state.php',
            'core/service/service_single_state.php',
            'core/service/session.php',
            'core/service/session_state.php',
            'core/service/session/inbuilt.php',
            'core/service/session/pear.php',
            'core/service/soap.php',
            'core/service/tab.php',
            'core/service/tab_state.php',
            'core/service/tab/delegate.php',
            'core/service/tab/delegate/urlMaker.php',
            'core/service/tab/engine.php',
            'core/service/tab/subscriber.php',
            'core/service/timer.php',
            'core/service/transfer.php',
            'core/service/translation.php',
            'core/service/user.php',
            'core/service/user_state.php',
            'core/service/user/base.php',
            'core/service/user/config.php',
            'core/service/user/entity.php',
            'core/view/definer.php',
            'core/view/keeper.php',
            'core/view/keeper/loader/json.php',
            'core/view/keeper/loader/text.php',
            'core/view/parser.php',
            'core/view/parser/debug1.php',
            'core/view/parser/debug2.php',
            'core/view/parser/html.php',
            'core/view/parser/json.php',
            'core/view/parser/loader.php',
            'core/view/parser/soap.php',
            'core/view/parser/xml.php',
            'core/view/router.php',
            'core/view/router/html.php',
            'core/view/router/json.php',
            'core/view/router/loader.php',
            'core/view/router/loader_state.php',
            'core/view/router/simple.php'
        ];
    }

    private function getCreatedTests(): array
    {
        return [
            'core/base/data.php' => 'unit/core/base/DataTest.php',
            'core/base/meta/delayed.php' => 'unit/core/base/meta/DelayedTest.php',
            'core/base/meta/maker.php' => 'unit/core/base/meta/MakerTest.php',
            'core/base/meta/maker_state.php' => 'unit/core/base/meta/MakerStateTest.php',
            'core/base/meta/row.php' => 'unit/core/base/meta/RowTest.php',
            'core/base/model/entity.php' => 'unit/core/base/model/EntityTest.php',
            'core/base/model/entity_dependencies.php' => 'unit/core/base/model/EntityTest.php',
            'core/base/model/file_data/entity.php' => 'unit/core/base/model/file_data/EntityTest.php',
            'core/base/model/file_data/row.php' => 'unit/core/base/model/file_data/RowTest.php',
            'core/base/model/request.php' => 'unit/core/base/model/RequestTest.php',
            'core/base/model/row.php' => 'unit/core/base/model/RowTest.php',
            'core/base/model/rowset.php' => 'unit/core/base/model/RowsetTest.php',
            'core/base/model/spec_file/entity.php' => 'unit/core/base/model/spec_file/EntityTest.php',
            'core/base/model/spec_file/image/entity.php' => 'unit/core/base/model/spec_file/image/EntityTest.php',
            'core/base/model/spec_file/image/row.php' => 'unit/core/base/model/spec_file/image/RowTest.php',
            'core/base/model/spec_file/image/row_state.php' => 'unit/core/base/model/spec_file/image/RowStateTest.php',
            'core/base/model/spec_file/row.php' => 'unit/core/base/model/spec_file/RowTest.php',
            'core/base/service.php' => 'unit/core/base/ServiceTest.php',
            'core/base/service/multi.php' => 'unit/core/base/service/MultiTest.php',
            'core/base/service/single.php' => 'unit/core/base/service/SingleTest.php',
            'core/base/timer_program.php' => 'unit/core/base/TimerProgramTest.php',
            'core/base/transfer.php' => 'unit/core/base/TransferTest.php',
            'core/base/transfer/int.php' => 'unit/core/base/transfer/IntTest.php',
            'core/base/transfer/out.php' => 'unit/core/base/transfer/OutTest.php',
            'core/base/transfer/sham.php' => 'unit/core/base/transfer/ShamTest.php',
            'core/base/transfer/transfer_int.php' => 'unit/core/base/transfer/TransferIntTest.php',
            'core/block/admin/base.php' => 'unit/core/block/admin/BaseTest.php',
            'core/block/admin/data.php' => 'unit/core/block/admin/DataTest.php',
            'core/block/admin/data_form.php' => 'unit/core/block/admin/DataFormTest.php',
            'core/block/admin/data_info.php' => 'unit/core/block/admin/DataInfoTest.php',
            'core/block/admin/data_table.php' => 'unit/core/block/admin/DataTableTest.php',
            'core/block/admin/form_pattern.php' => 'unit/core/block/admin/FormPatternTest.php',
            'core/block/admin/index.php' => 'unit/core/block/admin/IndexTest.php',
            'core/block/admin/root.php' => 'unit/core/block/admin/RootTest.php',
            'core/block/admin/select_dependent.php' => 'unit/core/block/admin/SelectDependentTest.php',
            'core/block/admin/structure.php' => 'unit/core/block/admin/StructureTest.php',
            'core/block/admin/upload_file.php' => 'unit/core/block/admin/UploadFileTest.php',
            'core/block/admin/upload_image.php' => 'unit/core/block/admin/UploadImageTest.php',
            'core/block/base.php' => 'unit/core/block/BaseTest.php',
            'core/block/base_dependency_defaults.php' => 'unit/core/block/BaseTest.php',
            'core/block/common/html_nav.php' => 'unit/core/block/common/HtmlNavTest.php',
            'core/block/common/html_nav_db.php' => 'unit/core/block/common/HtmlNavDbTest.php',
            'core/block/common/html_pager.php' => 'unit/core/block/common/HtmlPagerTest.php',
            'core/block/common/simple.php' => 'unit/core/block/common/SimpleTest.php',
            'core/block/error/error403.php' => 'unit/core/block/error/Error403Test.php',
            'core/block/error/error404.php' => 'unit/core/block/error/Error404Test.php',
            'core/block/error/error500.php' => 'unit/core/block/error/Error500Test.php',
            'core/block/loader/base.php' => 'unit/core/block/loader/BaseTest.php',
            'core/block/loader/loader_form_validation.php' => 'unit/core/block/loader/LoaderFormValidationTest.php',
            'core/block/root/html.php' => 'unit/core/block/root/HtmlTest.php',
            'core/application/application.php' => 'unit/core/application/ApplicationTest.php',
            'core/factory/application_container_defaults_factory.php' => 'unit/core/application/ApplicationContainerDefaultsFactoryTest.php',
            'core/factory/application_container_defaults_provider_factory.php' => 'unit/core/application/ApplicationContainerDefaultsProviderFactoryTest.php',
            'core/factory/application_container_creator_defaults_provider_factory.php' => 'unit/core/application/ApplicationContainerCreatorDefaultsProviderFactoryTest.php',
            'core/factory/application_container_factory_callable_factory.php' => 'unit/core/application/ApplicationContainerFactoryCallableFactoryTest.php',
            'core/factory/application_container_factory_provider_defaults_provider_factory.php' => 'unit/core/application/ApplicationContainerFactoryProviderDefaultsProviderFactoryTest.php',
            'core/factory/application_container_operations_defaults_provider_factory.php' => 'unit/core/application/ApplicationContainerOperationsDefaultsProviderFactoryTest.php',
            'core/factory/application_container_registrar_defaults_provider_factory.php' => 'unit/core/application/ApplicationContainerRegistrarDefaultsProviderFactoryTest.php',
            'core/factory/application_container_registry_defaults_provider_factory.php' => 'unit/core/application/ApplicationContainerRegistryDefaultsProviderFactoryTest.php',
            'core/factory/application_defaults_factory.php' => 'unit/core/application/ApplicationDefaultsFactoryTest.php',
            'core/factory/application_runtime_class_instantiator_provider.php' => 'unit/core/di/ApplicationRuntimeFactoryDefaultsProviderFactoryTest.php',
            'core/factory/application_runtime_configured_service_provider.php' => 'unit/core/di/ApplicationRuntimeFactoryDefaultsProviderFactoryTest.php',
            'core/factory/bootstrap_object_defaults_factory.php' => 'unit/core/application/BootstrapObjectDefaultsFactoryTest.php',
            'core/factory/bootstrap_object_class_instantiator_provider.php' => 'unit/core/application/BootstrapObjectDefaultsProviderFactoryTest.php',
            'core/factory/bootstrap_object_configured_service_provider.php' => 'unit/core/application/BootstrapObjectDefaultsProviderFactoryTest.php',
            'core/factory/bootstrap_object_defaults_provider_factory.php' => 'unit/core/application/BootstrapObjectDefaultsProviderFactoryTest.php',
            'core/factory/bootstrap_object_factory.php' => 'unit/core/application/BootstrapObjectFactoryTest.php',
            'core/factory/bootstrap_request_input_defaults_factory.php' => 'unit/core/application/BootstrapContextRequestInputDefaultsFactoryTest.php',
            'core/factory/bootstrap_runtime_defaults_factory.php' => 'unit/core/application/BootstrapRuntimeDefaultsFactoryTest.php',
            'core/factory/bootstrap_runtime_factory.php' => 'unit/core/application/BootstrapRuntimeFactoryTest.php',
            'core/factory/bootstrap_runtime_operations_defaults_provider_factory.php' => 'unit/core/application/BootstrapRuntimeOperationsDefaultsProviderFactoryTest.php',
            'core/factory/bootstrap_runtime_service_defaults_factory.php' => 'unit/core/application/BootstrapRuntimeServiceDefaultsFactoryTest.php',
            'core/factory/bootstrap_runtime_service_factory_defaults_provider_factory.php' => 'unit/core/application/BootstrapRuntimeServiceFactoryDefaultsProviderFactoryTest.php',
            'core/factory/bootstrap_runtime_service_defaults_provider_factory.php' => 'unit/core/application/BootstrapRuntimeServiceDefaultsProviderFactoryTest.php',
            'core/factory/bootstrap_runtime_state_defaults_factory.php' => 'unit/core/application/BootstrapRuntimeStateDefaultsFactoryTest.php',
            'core/factory/bootstrap_runtime_state_factory_defaults_provider_factory.php' => 'unit/core/application/BootstrapRuntimeStateFactoryDefaultsProviderFactoryTest.php',
            'core/factory/bootstrap_runtime_state_defaults_provider_factory.php' => 'unit/core/application/BootstrapRuntimeStateDefaultsProviderFactoryTest.php',
            'core/application/context_bootstrap_operations.php' => 'unit/core/application/ContextBootstrapOperationsTest.php',
            'core/factory/context_container_defaults_factory.php' => 'unit/core/application/ContextContainerDefaultsFactoryTest.php',
            'core/factory/context_core_defaults_factory.php' => 'unit/core/application/ContextCoreDefaultsFactoryTest.php',
            'core/factory/context_core_defaults_provider_factory.php' => 'unit/core/application/ContextCoreDefaultsProviderFactoryTest.php',
            'core/factory/context_defaults_factory.php' => 'unit/core/application/ContextDefaultsFactoryTest.php',
            'core/factory/context_support_defaults_factory.php' => 'unit/core/application/ContextSupportDefaultsFactoryTest.php',
            'core/factory/context_support_defaults_provider_factory.php' => 'unit/core/application/ContextSupportDefaultsProviderFactoryTest.php',
            'core/factory/runtime/error_handling_defaults_factory.php' => 'unit/core/application/ErrorHandlingDefaultsFactoryTest.php',
            'core/factory/runtime/error_logger_defaults_factory.php' => 'unit/core/application/ErrorLoggerDefaultsFactoryTest.php',
            'core/factory/error_logger_defaults_provider_factory.php' => 'unit/core/application/ErrorLoggerDefaultsProviderFactoryTest.php',
            'core/application/loader.php' => 'unit/core/application/LoaderTest.php',
            'core/application/request_runner.php' => 'unit/core/application/RequestRunnerTest.php',
            'core/factory/request_runner_defaults_factory.php' => 'unit/core/application/RequestRunnerDefaultsFactoryTest.php',
            'core/application/web_application_initializer.php' => 'unit/core/application/WebApplicationInitializerTest.php',
            'core/factory/web_application_initializer_defaults_factory.php' => 'unit/core/application/WebApplicationInitializerDefaultsFactoryTest.php',
            'core/factory/runtime/request_input_defaults_factory.php' => 'unit/core/application/RequestInputDefaultsFactoryTest.php',
            'core/factory/adapter/request_input_globals_factory.php' => 'unit/core/application/RequestInputGlobalsFactoryTest.php',
            'core/factory/runtime/request_input_factory.php' => 'unit/core/application/RequestInputFactoryTest.php',
            'core/factory/runtime/request_input_source_defaults_factory.php' => 'unit/core/application/RequestInputSourceDefaultsFactoryTest.php',
            'core/factory/request_input_source_defaults_provider_factory.php' => 'unit/core/application/RequestInputSourceDefaultsProviderFactoryTest.php',
            'core/factory/runtime/request_input_source_factory.php' => 'unit/core/application/RequestInputSourceFactoryTest.php',
            'core/application/runner.php' => 'unit/core/application/RunnerTest.php',
            'core/error/demonstrator.php' => 'unit/core/error/DemonstratorTest.php',
            'core/exception/base.php' => 'unit/core/exception/BaseTest.php',
            'core/exception/block/fatal.php' => 'unit/core/exception/block/FatalTest.php',
            'core/exception/block/local.php' => 'unit/core/exception/block/LocalTest.php',
            'core/exception/error500.php' => 'unit/core/exception/Error500Test.php',
            'core/exception/fatal.php' => 'unit/core/exception/FatalTest.php',
            'core/exception/model/reverse.php' => 'unit/core/exception/model/ReverseTest.php',
            'core/exception/plain/fatal.php' => 'unit/core/exception/plain/FatalTest.php',
            'core/exception/service/date.php' => 'unit/core/exception/service/DateTest.php',
            'core/exception/service/fatal.php' => 'unit/core/exception/service/FatalTest.php',
            'core/functions.php' => 'unit/core/FunctionsTest.php',
            'core/plain/db_file.php' => 'unit/core/plain/DbFileTest.php',
            'core/plain/image.php' => 'unit/core/plain/ImageTest.php',
            'core/plain/obfuscator.php' => 'unit/core/plain/ObfuscatorTest.php',
            'core/service/application.php' => 'unit/core/service/ApplicationTest.php',
            'core/service/block_context.php' => 'unit/core/service/BlockContextTest.php',
            'core/service/bootstrap_runtime.php' => 'unit/core/service/BootstrapRuntimeTest.php',
            'core/service/cache.php' => 'unit/core/service/CacheTest.php',
            'core/service/cache_memcache_state.php' => 'unit/core/service/CacheMemcacheStateTest.php',
            'core/service/cache_state.php' => 'unit/core/service/CacheStateTest.php',
            'core/service/cache/base.php' => 'unit/core/service/cache/BaseTest.php',
            'core/service/cache/file.php' => 'unit/core/service/cache/FileTest.php',
            'core/service/cache/memcache.php' => 'unit/core/service/cache/MemcacheTest.php',
            'core/service/cache/memcached.php' => 'unit/core/service/cache/MemcachedTest.php',
            'core/service/cache/wrapper/file_data.php' => 'unit/core/service/cache/wrapper/FileDataTest.php',
            'core/service/config.php' => 'unit/core/service/ConfigTest.php',
            'core/service/config_state.php' => 'unit/core/service/ConfigStateTest.php',
            'core/service/config/arr.php' => 'unit/core/service/config/ArrTest.php',
            'core/service/config/base.php' => 'unit/core/service/config/BaseTest.php',
            'core/service/config/row.php' => 'unit/core/service/config/RowTest.php',
            'core/service/config/xml.php' => 'unit/core/service/config/XmlTest.php',
            'core/service/config/yaml.php' => 'unit/core/service/config/YamlTest.php',
            'core/service/cookie.php' => 'unit/core/service/CookieTest.php',
            'core/service/cookie_state.php' => 'unit/core/service/CookieStateTest.php',
            'core/service/curl.php' => 'unit/core/service/CurlTest.php',
            'core/service/curl_state.php' => 'unit/core/service/CurlStateTest.php',
            'core/service/date.php' => 'unit/core/service/DateTest.php',
            'core/service/date_state.php' => 'unit/core/service/DateStateTest.php',
            'core/service/debug.php' => 'unit/core/service/DebugTest.php',
            'core/service/error.php' => 'unit/core/service/ErrorTest.php',
            'core/service/file_system.php' => 'unit/core/service/FileSystemTest.php',
            'core/service/file_system_state.php' => 'unit/core/service/FileSystemStateTest.php',
            'core/service/header.php' => 'unit/core/service/HeaderTest.php',
            'core/service/header/code.php' => 'unit/core/service/header/CodeTest.php',
            'core/service/image_draw.php' => 'unit/core/service/ImageDrawTest.php',
            'core/service/image_modify.php' => 'unit/core/service/ImageModifyTest.php',
            'core/service/image_modify_state.php' => 'unit/core/service/ImageModifyStateTest.php',
            'core/service/json.php' => 'unit/core/service/JsonTest.php',
            'core/service/json_state.php' => 'unit/core/service/JsonStateTest.php',
            'core/service/locale.php' => 'unit/core/service/LocaleTest.php',
            'core/service/matcher.php' => 'unit/core/service/MatcherTest.php',
            'core/service/matcher/item.php' => 'unit/core/service/matcher/ItemTest.php',
            'core/service/matcher/item/base.php' => 'unit/core/service/matcher/item/BaseTest.php',
            'core/service/matcher/item/handler.php' => 'unit/core/service/matcher/item/HandlerTest.php',
            'core/service/matcher/item/parsed.php' => 'unit/core/service/matcher/item/ParsedTest.php',
            'core/service/matcher/item/source.php' => 'unit/core/service/matcher/item/SourceTest.php',
            'core/service/matcher/item/uri.php' => 'unit/core/service/matcher/item/UriTest.php',
            'core/service/matcher/stack.php' => 'unit/core/service/matcher/StackTest.php',
            'core/service/obfuscator.php' => 'unit/core/service/ObfuscatorTest.php',
            'core/service/obfuscator_state.php' => 'unit/core/service/ObfuscatorStateTest.php',
            'core/service/obfuscator/base.php' => 'unit/core/service/obfuscator/BaseTest.php',
            'core/service/obfuscator/simple.php' => 'unit/core/service/obfuscator/SimpleTest.php',
            'core/service/pager.php' => 'unit/core/service/PagerTest.php',
            'core/service/pager_state.php' => 'unit/core/service/PagerStateTest.php',
            'core/service/plain.php' => 'unit/core/service/PlainTest.php',
            'core/service/plain_file_context.php' => 'unit/core/service/PlainFileContextTest.php',
            'core/service/reflector.php' => 'unit/core/service/ReflectorTest.php',
            'core/service/request.php' => 'unit/core/service/RequestTest.php',
            'core/service/request_input.php' => 'unit/core/service/RequestInputTest.php',
            'core/service/request_input_source.php' => 'unit/core/service/RequestInputSourceTest.php',
            'core/service/rest.php' => 'unit/core/service/RestTest.php',
            'core/service/rest_state.php' => 'unit/core/service/RestStateTest.php',
            'core/service/role.php' => 'unit/core/service/RoleTest.php',
            'core/service/service_listener_state.php' => 'unit/core/service/ServiceListenerStateTest.php',
            'core/service/service_single_state.php' => 'unit/core/service/ServiceSingleStateTest.php',
            'core/service/session.php' => 'unit/core/service/SessionTest.php',
            'core/service/session_state.php' => 'unit/core/service/SessionStateTest.php',
            'core/service/session/inbuilt.php' => 'unit/core/service/session/InbuiltTest.php',
            'core/service/session/pear.php' => 'unit/core/service/session/PearTest.php',
            'core/service/soap.php' => 'unit/core/service/SoapTest.php',
            'core/service/tab.php' => 'unit/core/service/TabTest.php',
            'core/service/tab_state.php' => 'unit/core/service/TabStateTest.php',
            'core/service/tab/delegate.php' => 'unit/core/service/tab/DelegateTest.php',
            'core/service/tab/delegate/urlMaker.php' => 'unit/core/service/tab/delegate/UrlMakerTest.php',
            'core/service/tab/engine.php' => 'unit/core/service/tab/EngineTest.php',
            'core/service/tab/subscriber.php' => 'unit/core/service/tab/SubscriberTest.php',
            'core/service/timer.php' => 'unit/core/service/TimerTest.php',
            'core/service/transfer.php' => 'unit/core/service/TransferTest.php',
            'core/service/translation.php' => 'unit/core/service/TranslationTest.php',
            'core/service/user.php' => 'unit/core/service/UserTest.php',
            'core/service/user_state.php' => 'unit/core/service/UserStateTest.php',
            'core/service/user/base.php' => 'unit/core/service/user/BaseTest.php',
            'core/service/user/config.php' => 'unit/core/service/user/ConfigTest.php',
            'core/service/user/entity.php' => 'unit/core/service/user/EntityTest.php',
            'core/view/definer.php' => 'unit/core/view/DefinerTest.php',
            'core/view/keeper.php' => 'unit/core/view/KeeperTest.php',
            'core/view/keeper/loader/json.php' => 'unit/core/view/keeper/loader/JsonTest.php',
            'core/view/keeper/loader/text.php' => 'unit/core/view/keeper/loader/TextTest.php',
            'core/view/parser.php' => 'unit/core/view/ParserTest.php',
            'core/view/parser/debug1.php' => 'unit/core/view/parser/Debug1Test.php',
            'core/view/parser/debug2.php' => 'unit/core/view/parser/Debug2Test.php',
            'core/view/parser/html.php' => 'unit/core/view/parser/HtmlTest.php',
            'core/view/parser/json.php' => 'unit/core/view/parser/JsonTest.php',
            'core/view/parser/loader.php' => 'unit/core/view/parser/LoaderTest.php',
            'core/view/parser/soap.php' => 'unit/core/view/parser/SoapTest.php',
            'core/view/parser/xml.php' => 'unit/core/view/parser/XmlTest.php',
            'core/view/router.php' => 'unit/core/view/RouterTest.php',
            'core/view/router/html.php' => 'unit/core/view/router/HtmlTest.php',
            'core/view/router/json.php' => 'unit/core/view/router/JsonTest.php',
            'core/view/router/loader.php' => 'unit/core/view/router/LoaderTest.php',
            'core/view/router/loader_state.php' => 'unit/core/view/router/LoaderStateTest.php',
            'core/view/router/simple.php' => 'unit/core/view/router/SimpleTest.php'
        ];
    }

    private function getSkippedSourceFiles(): array
    {
        return [
            'core/block/admin/data.meta.php' => 'metadata array/configuration file; no executable unit behavior beyond framework loading',
            'core/block/admin/data_form.meta.php' => 'metadata array/configuration file; no executable unit behavior beyond framework loading',
            'core/block/admin/data_info.meta.php' => 'metadata array/configuration file; no executable unit behavior beyond framework loading',
            'core/block/admin/data_table.meta.php' => 'metadata array/configuration file; no executable unit behavior beyond framework loading',
            'core/block/admin/form_pattern.meta.php' => 'metadata array/configuration file; no executable unit behavior beyond framework loading',
            'core/block/admin/index.meta.php' => 'metadata array/configuration file; no executable unit behavior beyond framework loading',
            'core/block/admin/root.meta.php' => 'metadata array/configuration file; no executable unit behavior beyond framework loading',
            'core/block/admin/structure.meta.php' => 'metadata array/configuration file; no executable unit behavior beyond framework loading',
            'core/block/common/html_pager.meta.php' => 'metadata array/configuration file; no executable unit behavior beyond framework loading',
            'core/block/root/html.meta.php' => 'metadata array/configuration file; no executable unit behavior beyond framework loading',
            'core/application/initializer.php' => 'bootstrap/runtime wiring file with global side effects; integration/bootstrap coverage is safer than isolated unit loading',
            'core/error/template/default.php' => 'presentation template fragment; behavior belongs to renderer/error service integration',
            'core/error/template/error_403.php' => 'presentation template fragment; behavior belongs to renderer/error service integration',
            'core/error/template/error_404.php' => 'presentation template fragment; behavior belongs to renderer/error service integration',
            'core/error/template/error_500.php' => 'presentation template fragment; behavior belongs to renderer/error service integration'
        ];
    }

    public function testEveryCorePhpSourceFileIsClassified(): void
    {
        $classified = array_merge(array_keys($this->getCreatedTests()), array_keys($this->getSkippedSourceFiles()));
        sort($classified);
        $discovered = $this->getDiscoveredSourceFiles();
        sort($discovered);
        $this->assertSame($discovered, $classified);
    }

    public function testCreatedTestFilesExistInPreservedUnitTree(): void
    {
        $root = dirname(dirname(__DIR__));
        foreach ($this->getCreatedTests() as $source => $test) {
            $this->assertSame(0, strpos($test, 'unit/'), $source);
            $this->assertFileExists($root . '/' . $test, $source);
        }
    }

    public function testSkippedFilesHaveExplicitReasons(): void
    {
        foreach ($this->getSkippedSourceFiles() as $source => $reason) {
            $this->assertNotEmpty($reason, $source);
        }
    }
}
